contact_links:
  - name: ğŸ“š Docs
    url: https://github.com/BetaHuhn/metadata-scraper#%EF%B8%8F-configuration
    about: Checkout metadata-scraper's documentation before you open an issue.
  - name: ğŸ› ï¸ Examples
    url: https://github.com/BetaHuhn/metadata-scraper#%EF%B8%8F-examples
    about: Checkout a view examples on how to use metadata-scraper.